apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-data
spec:
  capacity:
    storage: 1800Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1800Gi