apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}
data:
  config.yaml: |
    log_level: INFO

    mqtt:
      address: 192.168.1.202
      port: 1883
      repeat_time: 10

      main_topic: modbus-to-mqtt

    fieldbus:
      address: "192.168.1.12"

      read:
      - type: coil
        start: 0
        count: 32

      scan_time: 80
      long_press_time: 1000