apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: devops
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 0.9.2
    chart: alloy
    helm:
      values: |
        fullnameOverride: alloy

        controller:
          type: daemonset

        tolerations:
        - operator: "Exists"

        ingress:
          enabled: true
          faroPort: 12345
          hosts:
            - alloy.priv

        alloy:
        
          clustering: 
            enabled: true

          stabilityLevel: "experimental"

          enableReporting: false

          configReloader:
            enabled: false

          configMap:
            content:

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:  
    automated:
      prune: true
      selfHeal: true