apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: devops
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 0.9.2
    chart: grafana/alloy
    helm:
      values: |
        fullnameOverride: alloy

        controller:
          type: daemonset

        tolerations:
        - operator: "Exists"

        ingress:

          extraPaths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ssl-redirect
                port:
                  name: use-annotation

        alloy:
        
          clustering: 
            enabled: true

          stabilityLevel: "experimental"

          enableReporting: false

          configReloader:
            enabled: false

          configMap:
            content:

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:  
    automated:
      prune: true
      selfHeal: true