apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: devops
spec:
  project: default
  source:
    repoURL: ghcr.io/matlerbru/charts
    targetRevision: 0.1.2
    chart: home-assistant
    helm:
      values: |
        config:
          http:
            use_x_forwarded_for: true
            trusted_proxies: 10.0.0.0/16

          homeassistant:
            latitude: 57.16355909024812
            longitude: 10.150039286435732
            unit_system: metric 
            time_zone: Europe/Copenhagen
            name: Konstantinsvej 2

          mqtt:
            sensor:
              - name: "modbus press"
                state_topic: "modbus-to-mqtt/output"

          mobile_app:

          automation lights:
          - alias: Livingroom light toggle
            description: ""
            trigger:
              - platform: mqtt
                topic: modbus-to-mqtt/output
                payload: "{\"address\": 1, \"press\": \"short\"}"
            condition: []
            action:
              - type: toggle
                device_id: 9b59cff9c86371925ef4662f0451f397
                entity_id: 24e0365b841879141592e63f6aa8b737
                domain: light
              - domain: light
                device_id: 1579f4b0f626aa805217cdfb8d0afb77
                entity_id: 501738621f329b91769b6be928d90b7f
                type: toggle
            mode: single

          - alias: Livingroom light dim
            description: ""
            trigger:
              - platform: mqtt
                topic: modbus-to-mqtt/output
                payload: "{\"address\": 5, \"press\": \"short\"}"
            condition: []
            action:
              - domain: light
                type: brightness_decrease
                device_id: 9b59cff9c86371925ef4662f0451f397
                entity_id: 24e0365b841879141592e63f6aa8b737
              - domain: light
                device_id: 1579f4b0f626aa805217cdfb8d0afb77
                entity_id: 501738621f329b91769b6be928d90b7f
                type: brightness_decrease
            mode: single

          - alias: Livingroom light bright
            description: ""
            trigger:
              - platform: mqtt
                topic: modbus-to-mqtt/output
                payload: "{\"address\": 4, \"press\": \"short\"}"
            condition: []
            action:
              - domain: light
                device_id: 9b59cff9c86371925ef4662f0451f397
                entity_id: 24e0365b841879141592e63f6aa8b737
                type: brightness_increase
              - domain: light
                device_id: 1579f4b0f626aa805217cdfb8d0afb77
                entity_id: 501738621f329b91769b6be928d90b7f
                type: brightness_increase
            mode: single

          - alias: Livingroom shelves light toggle
            description: ""
            trigger:
              - platform: mqtt
                topic: modbus-to-mqtt/output
                payload: "{\"address\": 0, \"press\": \"short\"}"
            condition: []
            action:
              - type: toggle
                device_id: 1579f4b0f626aa805217cdfb8d0afb77
                entity_id: 501738621f329b91769b6be928d90b7f
                domain: switch
            mode: single

          - alias: Livingroom shelves light on
            description: ""
            trigger:
              - platform: device
                type: turned_on
                device_id: 9b59cff9c86371925ef4662f0451f397
                entity_id: 24e0365b841879141592e63f6aa8b737
                domain: light
            condition: []
            action:
              - type: turn_on
                device_id: 1579f4b0f626aa805217cdfb8d0afb77
                entity_id: 501738621f329b91769b6be928d90b7f
                domain: switch
            mode: single

          - alias: Livingroom shelves light off
            description: ""
            trigger:
              - platform: device
                type: turned_off
                device_id: 9b59cff9c86371925ef4662f0451f397
                entity_id: 24e0365b841879141592e63f6aa8b737
                domain: light
            condition: []
            action:
              - type: turn_off
                device_id: 1579f4b0f626aa805217cdfb8d0afb77
                entity_id: 501738621f329b91769b6be928d90b7f
                domain: switch
            mode: single

          - alias: Kitchen light toggle
            description: ""
            trigger:
              - platform: mqtt
                topic: modbus-to-mqtt/output
                payload: "{\"address\": 13, \"press\": \"short\"}"
            condition: []
            action:
              - type: toggle
                device_id: 9a583ab3611e2f76ce766189798385ce
                entity_id: 1f9e65efd24a0d25161c37d9b946bb2d
                domain: light
            mode: single

          - alias: Kitchen light dim
            description: ""
            trigger:
              - platform: mqtt
                topic: modbus-to-mqtt/output
                payload: "{\"address\": 9, \"press\": \"short\"}"
            condition: []
            action:
              - device_id: 9a583ab3611e2f76ce766189798385ce
                entity_id: 1f9e65efd24a0d25161c37d9b946bb2d
                domain: light
                type: brightness_decrease
            mode: single

          - alias: Kitchen light bright
            description: ""
            trigger:
              - platform: mqtt
                topic: modbus-to-mqtt/output
                payload: "{\"address\": 8, \"press\": \"short\"}"
            condition: []
            action:
              - device_id: 9a583ab3611e2f76ce766189798385ce
                entity_id: 1f9e65efd24a0d25161c37d9b946bb2d
                domain: light
                type: brightness_increase
            mode: single

          - alias: Bathroom light toggle
            description: ""
            trigger:
              - platform: mqtt
                topic: modbus-to-mqtt/output
                payload: "{\"address\": 16, \"press\": \"short\"}"
            condition: []
            action:
              - type: toggle
                device_id: bcda68128afaa62b6b9f41e73c88ad49
                entity_id: 2f99487fa0c2a1a894c16affa56f66b7
                domain: light
            mode: single

          - alias: Bathroom light dim
            description: ""
            trigger:
              - platform: mqtt
                topic: modbus-to-mqtt/output
                payload: "{\"address\": 18, \"press\": \"short\"}"
            condition: []
            action:
                device_id: bcda68128afaa62b6b9f41e73c88ad49
                entity_id: 2f99487fa0c2a1a894c16affa56f66b7
                domain: light
                type: brightness_decrease
            mode: single

          - alias: Bathroom light bright
            description: ""
            trigger:
              - platform: mqtt
                topic: modbus-to-mqtt/output
                payload: "{\"address\": 19, \"press\": \"short\"}"
            condition: []
            action:
              - domain: light
                device_id: bcda68128afaa62b6b9f41e73c88ad49
                entity_id: 2f99487fa0c2a1a894c16affa56f66b7
                type: brightness_increase
            mode: single

          - alias: Bathroom mirror toggle
            description: ""
            trigger:
              - platform: mqtt
                topic: modbus-to-mqtt/output
                payload: "{\"address\": 17, \"press\": \"short\"}"
            condition: []
            action:
              - type: toggle
                device_id: 4bdb46c90ce1927f1e3a15616fc72dcf
                entity_id: 35297a106b477953a46f53d4f2fab091
                domain: switch
            mode: single

          - alias: Bathroom mirror on
            description: ""
            trigger:
              - platform: device
                type: turned_on
                device_id: bcda68128afaa62b6b9f41e73c88ad49
                entity_id: 2f99487fa0c2a1a894c16affa56f66b7
                domain: light
            condition: []
            action:
              - type: turn_on
                device_id: 4bdb46c90ce1927f1e3a15616fc72dcf
                entity_id: 35297a106b477953a46f53d4f2fab091
                domain: switch
            mode: single

          - alias: Bathroom mirror off
            description: ""
            trigger:
              - platform: device
                type: turned_off
                device_id: bcda68128afaa62b6b9f41e73c88ad49
                entity_id: 2f99487fa0c2a1a894c16affa56f66b7
                domain: light
            condition: []
            action:
              - type: turn_off
                device_id: 4bdb46c90ce1927f1e3a15616fc72dcf
                entity_id: 35297a106b477953a46f53d4f2fab091
                domain: switch
            mode: single

          - alias: Playroom light toggle
            description: ""
            trigger:
              - platform: mqtt
                topic: modbus-to-mqtt/output
                payload: "{\"address\": \"6\", \"press\": \"short\"}"
            condition: []
            action:
              - type: toggle
                device_id: 5a87c5642cb904dbe23ccd3f5761cdbc
                entity_id: 266c55f3eba55b4de3566c5e837e4ce6
                domain: light
            mode: single

          - alias: Playroom light dim
            description: ""
            trigger:
              - platform: mqtt
                topic: modbus-to-mqtt/output
                payload: "{\"address\": \"2\", \"press\": \"short\"}"
            condition: []
            action:
              - device_id: 5a87c5642cb904dbe23ccd3f5761cdbc
                entity_id: 266c55f3eba55b4de3566c5e837e4ce6
                domain: light
                type: brightness_decrease
            mode: single

          - alias: Playroom light bright
            description: ""
            trigger:
              - platform: mqtt
                topic: modbus-to-mqtt/output
                payload: "{\"address\": \"3\", \"press\": \"short\"}"
            condition: []
            action:
              - device_id: 5a87c5642cb904dbe23ccd3f5761cdbc
                entity_id: 266c55f3eba55b4de3566c5e837e4ce6
                domain: light
                type: brightness_increase
            mode: single
  destination:
    server: https://kubernetes.default.svc
    namespace: home
  syncPolicy:  
    automated:
      prune: true
      selfHeal: true