apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: unifi
  namespace: devops
spec:
  project: default
  source:
    repoURL: ghcr.io/matlerbru/charts
    targetRevision: 0.2.0
    chart: unifi-controller
  destination:
    server: https://kubernetes.default.svc
    namespace: home
  syncPolicy:  
    automated:
      prune: true
      selfHeal: true