apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: modbus-to-mqtt
  namespace: home
spec:
  project: default
  source:
    repoURL: https://ghcr.io/matlerbru/charts
    targetRevision: 0.1.0
    chart: modbus-to-mqtt
  destination:
    server: https://kubernetes.default.svc
    namespace: home
  syncPolicy:  
    automated:
      prune: true
      selfHeal: true