apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-credentials
  namespace: monitoring
spec:
  encryptedData:
    password: AgAsjhpMrQ/ae+HHRySLibD/zfbSbP26IgU1cdkWaANFbWvfnRjQrXosVzYay+75J6e/A93j6M2snD5doaaU05IlxalhXv453Hn3HK67/ob67uHhcNLqJEEniTG4Lpl9Jj5gYtR/Vjluw3HM2yTJ/AvMN7SIDWfl4IIBjWDAepKF60XNlEA8nro+y3GDy/yTE4VLPOgPh9I300JgRn+Siy1VW42UK09qsP6jvtlpSZkHxH+hkXuVa9wBnBNMDM1MsytEbHvJJCXk+64oM0EZaLUiuBR5sU/pb4R+wkEZwBPEIEtMF5EQlJ9QMAlT4/X40fknJQQdmSfijD00S+D1AH6i4GH58GY/160nMqPu95ZfggkEyGRNnCOP7xejnArMxf/LmXkMfLwFSnEuZ9vh0IwTCwtxOEbqSX6JoFnvQVPLbpbWgm462346nZWCUCCVF6YGI9ke4gzYtK5ueoo5fbnI9p1Ltbyua2HRANhDV+IpafnUoSDMN0bSIBvuKQ/COtVES1ihOyv13/0dMyFpHzyxlsY1hEVSQ26eNb8q8En3g1JKhaf5rhvdp8FZ1Xr7LdbXDMpUFpDmKFvaSiJjaXDtaxPo5La/nHy3HMfboWx2V1PZA32OZs4XgsBvnD5WJ/+KUu+Io/y/vLaeQlIOWVD9iJrM5CUFq/7E7pMAMWs526FgKzIJqrXdLMkYMXr5jpc9MFWVqPw0zp3Hf7xj+Efda6UAkOJR6Fk7ND2h7e66pMRj2TGC5FdV
    username: AgCix8z//PssKxVzMYj9nHTgIqM1nwnn1xo5J2foBjbJ5v7nkDBJpgH02qebn0qLIFOeJkqiy8QqtoKDDZoSRMz4/UBJKSGu/D4DLiJlegQLHl7h5dfYaEonFdZ8gTZeDM7h0xIC5UFTw3qLLCxWhBX38LPJxYeeyaQa92TQWwqUU6QDKjL22lsmWtLb9+GQBh0o9TgzZdxnk8hLacRJj0eaiq/8L+mpDMiPVvf+eLKDibvm7g7+H8Gp2CYB7h5N0IJN4juG+kAeRHtAmHxFtoYs6V+UsM8FH/F0XJiMPRlJWIj8H11KStLSCQBJs6mkpM1jQXCiraAf0OCFGHeXYQ7g4csz/glhkJz+KLEVSducTNaY9CkkiCbiEU0iyvG+eWTcZoGOTF5emvOxUlRYHYvwFt96/qeHxOIZ3MRoV6KPdJlred5IhRi+xdenSZcFyk3qUr1OwuY3p7dCqyLD14YSaw74aZwiYkbbL9HW8sMqw32yjyPJJGFBkFvh/qdAWjMzseoIB/P/GUdv6FNfFYxk8ME5ztoovhRvkZCe57fpqDpDRtVyJ4+Nc3sD/K+74CkqYBj5aHh/ysbfNcnv/3h6tmFs8OSnHo/xZTTQpa/5miAnK3NYeqzd7nobxfzguaHAKPn2rwGP8m/4uNSaNtHVa2aPRDQF5WS3uTB7c58WxE9zEAmyfRHxZhBL7kMPSAn6rH7gow==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-credentials
      namespace: monitoring