apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tstack-credentials
  namespace: torrent
spec:
  encryptedData:
    password: AgBIS0pzjukvg+8AsNzVRpO+yvxdR7x4KTPhCrPGFfOpUnnZ3szVZ3L4NcFAU0JS8W9+aVLVm8vG8AMmYg/T5yLgqLx4xH1pwsufTbzREe/VUtXzka1HLKtBxTl9L8moFrQDoZcWxTcgPAQ6EwQia7uNx2ejJoMsFmepJ4dYBzttl6oQb3En1SPsfK4rmL4uOkV+sMGNnqNyDwkmdOmiGZsYUufJY3asY2c/TxriRCy5uyhFPLjiPpvU/xed8IaaMZpZGUMx8pX1I4ICVaYhm/1rpG7yIM32jOfl7t8noxaKloKHrKKD4WlGSmkRIgfJ39xWqVQMOgs/NfnoqnxhrxQQT0vv2l0wvadBYbhLnG+NPmZb9jRP4SAFrIBzGiECeaOvfmKDX9KXj+rp3O+aHYQq0rgadgE2GfahXublaSKNNZuhwZavOOO7OLYnZJOq/FaPKrVIAlcI/z3Dt7WsLSt83p0+t7rcrqtS+lBbCOpS3mhRY1vu0J+W2o99/eNCxy3UNQtsO68ABWXAtqbQkPWTPT3RG0eZIEAoG+JyK8Y3q+RcojuJoye//QIgy93AuJS6XOZzYf9Ee3ACBEEYiXtTolptau3smjkpiCd8IBY5+DohlqzZuSxj1ZUt18hrx9KpHzr3ZusMyTFm/fvuLJesHZ5Tz/mN6WSaQKHMi2TifB55m5UDERji6SJJLFRu0VIImX1nDQZuXVFCi0t9yIQ=
    username: AgBXbR/sRAgF/Xi7CvQLX2ZL8E7RR/p2IhTGOUIPov+hbwFVeCx/0iPsppzsFkr7um41EL5t4pm4dV8Spk8uePNEHkrN4cixbsnaxv0TdJ9K4zP5GC3Mr2dNkQOLL2esKlmDRiytgvKVNjDT13YR4BckAQhdgrAVUHf+siAqhVFnTqIQhQHWat4EbcMLxzhE1aFZeFWaLfE1W4wWow3+UOoBsreL7k+u1Ux3iECvd7Iin7dtkox7P+ORx+OflDtgulUJ3UGISkpv6LTtkK3TZaEoc3i/tJ0uRsxuIxibHI2aQKgKeggPwIUoBH2qfQWHrhcyuR5uFA1G4uMvDy0PlOQH9mEQBHG6OENfZNO+KctGV0mXi5buhC1KW5gL27bGGXbLM6VrpLaoaFfBcygJkCGKNIXmx8eOJ+qq1ME11nA+LVvZVWryHLeYzm/zNpjWV9R3htvc5uAADNbiKTifp5CCAhX9ebWYP7iOt3cshC9dpk4dEfMhQbNlNw/xk/IMSVYWfUztWZEE3LMvK+VCrSDA+vkMhUGkpHtAO/LzHrgy7yxhouk1Qc4yEXbX1i3gD1SZzNI+HPiVFEjzxqzPAie5Slf9zknQz+HEwoCD8A6svrdI4d5rUWegw1UHyCFW8WUdi+s8ktxoQ/FSu6+RZxlVcPaNMbcBG89hofefiJvAkMPVKbHDcR1WWXMTROmB4oCD6d7qECDKIGjmuarGH1Um8ynVmw==
  template:
    metadata:
      creationTimestamp: null
      name: tstack-credentials
      namespace: torrent